# Generated by Django 3.2.8 on 2022-02-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='pic',
            new_name='image',
        ),
    ]
