# Generated by Django 3.2.8 on 2022-02-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
