# Generated by Django 3.2.8 on 2022-02-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bids_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
