# Generated by Django 3.2.8 on 2022-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20220220_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
