# Generated by Django 3.2.8 on 2022-02-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
