# Generated by Django 3.2.8 on 2022-02-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20220222_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('usr_account', models.CharField(max_length=64)),
                ('comment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_item', to='auctions.listing')),
            ],
        ),
    ]
