# Generated by Django 3.2.8 on 2022-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
